.\" Copyright (C) 2010 Romain Tartiere
.\"
.\" This program is free software: you can redistribute it and/or modify it
.\" under the terms of the GNU Lesser General Public License as published by the
.\" Free Software Foundation, either version 3 of the License, or (at your
.\" option) any later version.
.\"
.\" This program is distributed in the hope that it will be useful, but WITHOUT
.\" ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
.\" FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License for
.\" more details.
.\"
.\" You should have received a copy of the GNU Lesser General Public License
.\" along with this program.  If not, see <http://www.gnu.org/licenses/>
.\"
.\" $Id: ucard-explain.1 552 2010-12-07 13:09:10Z romain $
.\"
.Dd December 7, 2010
.Dt UCARD-EXPLAIN 1
.Os
.Sh NAME
.Nm ucard-explain
.Nd UCard Meta-data Extraction Tool
.Sh SYNOPSIS
.Nm
.Sh DESCRIPTION
The
.Nm
utility displays information about all UCard in proximity of NFC couplers.
.Sh AUTHORS
.An Romain Tartiere Aq rtartiere@il4p.fr
