/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class net_raisama_nfc_mfoc_NativeImplementation */

#ifndef _Included_net_raisama_nfc_mfoc_NativeImplementation
#define _Included_net_raisama_nfc_mfoc_NativeImplementation
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     net_raisama_nfc_mfoc_NativeImplementation
 * Method:    sum
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_net_raisama_nfc_mfoc_NativeImplementation_sum
  (JNIEnv *, jobject, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
