/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class net_raisama_nfc_mfoc_NativeImplementation */

#ifndef _Included_net_raisama_nfc_mfoc_NativeImplementation
#define _Included_net_raisama_nfc_mfoc_NativeImplementation
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     net_raisama_nfc_mfoc_NativeImplementation
 * Method:    nativeMain
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_net_raisama_nfc_mfoc_NativeImplementation_nativeMain
  (JNIEnv *, jobject);

/*
 * Class:     net_raisama_nfc_mfoc_NativeImplementation
 * Method:    setFakeStdioObject
 * Signature: (Lnet/raisama/nfc/mfoc/FakeStdio;Lnet/raisama/nfc/mfoc/FakeFile;Lnet/raisama/nfc/mfoc/FakeFile;)V
 */
JNIEXPORT void JNICALL Java_net_raisama_nfc_mfoc_NativeImplementation_setFakeStdioObject
  (JNIEnv *, jobject, jobject, jobject, jobject);

/*
 * Class:     net_raisama_nfc_mfoc_NativeImplementation
 * Method:    setFakeLibNFC
 * Signature: (Lnet/raisama/nfc/mfoc/FakeLibNFC;)V
 */
JNIEXPORT void JNICALL Java_net_raisama_nfc_mfoc_NativeImplementation_setFakeLibNFC
  (JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
